# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addnode_form.ui',
# licensing of 'addnode_form.ui' applies.
#
# Created: Sun Aug 23 19:44:42 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(459, 522)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.tbName = QtWidgets.QLineEdit(self.frame_2)
        self.tbName.setObjectName("tbName")
        self.horizontalLayout_2.addWidget(self.tbName)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMinimumSize(QtCore.QSize(60, 0))
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.errUniqueName = QtWidgets.QLabel(Dialog)
        self.errUniqueName.setObjectName("errUniqueName")
        self.verticalLayout.addWidget(self.errUniqueName)
        self.frmParent = QtWidgets.QFrame(Dialog)
        self.frmParent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmParent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmParent.setObjectName("frmParent")
        self.gridLayout = QtWidgets.QGridLayout(self.frmParent)
        self.gridLayout.setObjectName("gridLayout")
        self.cbParentAxis = QtWidgets.QComboBox(self.frmParent)
        self.cbParentAxis.setObjectName("cbParentAxis")
        self.gridLayout.addWidget(self.cbParentAxis, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frmParent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(80, 0))
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frmParent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(60, 0))
        self.label_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.frmParent)
        self.frmParentPoi = QtWidgets.QFrame(Dialog)
        self.frmParentPoi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmParentPoi.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmParentPoi.setObjectName("frmParentPoi")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frmParentPoi)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cbParentPoi = QtWidgets.QComboBox(self.frmParentPoi)
        self.cbParentPoi.setObjectName("cbParentPoi")
        self.gridLayout_4.addWidget(self.cbParentPoi, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frmParentPoi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(80, 0))
        self.label_13.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frmParentPoi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(60, 0))
        self.label_14.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.frmParentPoi)
        self.frmMasterSlave = QtWidgets.QFrame(Dialog)
        self.frmMasterSlave.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmMasterSlave.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmMasterSlave.setObjectName("frmMasterSlave")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frmMasterSlave)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.frmMasterSlave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(80, 0))
        self.label_6.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.cbMasterAxis = QtWidgets.QComboBox(self.frmMasterSlave)
        self.cbMasterAxis.setObjectName("cbMasterAxis")
        self.gridLayout_2.addWidget(self.cbMasterAxis, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frmMasterSlave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(60, 0))
        self.label_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frmMasterSlave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(80, 0))
        self.label_8.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.cbSlaveAxis = QtWidgets.QComboBox(self.frmMasterSlave)
        self.cbSlaveAxis.setObjectName("cbSlaveAxis")
        self.gridLayout_2.addWidget(self.cbSlaveAxis, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frmMasterSlave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(60, 0))
        self.label_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.frmMasterSlave)
        self.frmPoints = QtWidgets.QFrame(Dialog)
        self.frmPoints.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmPoints.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmPoints.setObjectName("frmPoints")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frmPoints)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(self.frmPoints)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(80, 0))
        self.label_10.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.cbPoiA = QtWidgets.QComboBox(self.frmPoints)
        self.cbPoiA.setObjectName("cbPoiA")
        self.gridLayout_3.addWidget(self.cbPoiA, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frmPoints)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(60, 0))
        self.label_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frmPoints)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(80, 0))
        self.label_12.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.cbPoiB = QtWidgets.QComboBox(self.frmPoints)
        self.cbPoiB.setObjectName("cbPoiB")
        self.gridLayout_3.addWidget(self.cbPoiB, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frmPoints)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(60, 0))
        self.label_11.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.frmPoints)
        self.errPois = QtWidgets.QLabel(Dialog)
        self.errPois.setObjectName("errPois")
        self.verticalLayout.addWidget(self.errPois)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnOk = QtWidgets.QPushButton(self.frame)
        self.btnOk.setAutoDefault(False)
        self.btnOk.setDefault(True)
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout.addWidget(self.btnOk)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "New Node", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Name", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "[unique]", None, -1))
        self.errUniqueName.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">Pick a unique name !</span></p></body></html>", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Parent", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "[axis]", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Dialog", "Parent", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Dialog", "[poi]", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Main", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "[axis]", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog", "Secondary", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "[axis]", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Dialog", "point 1", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Dialog", "[poi]", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Dialog", "point 2", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Dialog", "[poi]", None, -1))
        self.errPois.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">Select two distinct pois</span></p></body></html>", None, -1))
        self.btnOk.setText(QtWidgets.QApplication.translate("Dialog", "  Ok  ", None, -1))

