# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_nodetypes.ui',
# licensing of 'menu_nodetypes.ui' applies.
#
# Created: Tue Aug  4 16:46:20 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MenuNodes(object):
    def setupUi(self, MenuNodes):
        MenuNodes.setObjectName("MenuNodes")
        MenuNodes.resize(703, 539)
        self.gridLayout = QtWidgets.QGridLayout(MenuNodes)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(MenuNodes)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pbPoint = QtWidgets.QPushButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/point_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbPoint.setIcon(icon)
        self.pbPoint.setFlat(True)
        self.pbPoint.setObjectName("pbPoint")
        self.verticalLayout.addWidget(self.pbPoint)
        self.pbCircle = QtWidgets.QPushButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/circle_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbCircle.setIcon(icon1)
        self.pbCircle.setFlat(True)
        self.pbCircle.setObjectName("pbCircle")
        self.verticalLayout.addWidget(self.pbCircle)
        self.pbAxis = QtWidgets.QPushButton(self.widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/axis_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbAxis.setIcon(icon2)
        self.pbAxis.setFlat(True)
        self.pbAxis.setObjectName("pbAxis")
        self.verticalLayout.addWidget(self.pbAxis)
        self.pbBody = QtWidgets.QPushButton(self.widget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/cube.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbBody.setIcon(icon3)
        self.pbBody.setFlat(True)
        self.pbBody.setObjectName("pbBody")
        self.verticalLayout.addWidget(self.pbBody)
        self.pbGeometricContact = QtWidgets.QPushButton(self.widget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/pin_hole.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbGeometricContact.setIcon(icon4)
        self.pbGeometricContact.setFlat(True)
        self.pbGeometricContact.setObjectName("pbGeometricContact")
        self.verticalLayout.addWidget(self.pbGeometricContact)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(MenuNodes)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.pbContactShape = QtWidgets.QPushButton(self.widget_5)
        self.pbContactShape.setStyleSheet("text-align:left")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/trimesh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbContactShape.setIcon(icon5)
        self.pbContactShape.setFlat(True)
        self.pbContactShape.setObjectName("pbContactShape")
        self.verticalLayout_5.addWidget(self.pbContactShape)
        self.pbContactBall = QtWidgets.QPushButton(self.widget_5)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/contactball.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbContactBall.setIcon(icon6)
        self.pbContactBall.setFlat(True)
        self.pbContactBall.setObjectName("pbContactBall")
        self.verticalLayout_5.addWidget(self.pbContactBall)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.gridLayout.addWidget(self.widget_5, 0, 5, 1, 1)
        self.widget_6 = QtWidgets.QWidget(MenuNodes)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.pbSpring2D = QtWidgets.QPushButton(self.widget_6)
        self.pbSpring2D.setStyleSheet("text-align:left")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/con2d.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSpring2D.setIcon(icon7)
        self.pbSpring2D.setFlat(True)
        self.pbSpring2D.setObjectName("pbSpring2D")
        self.verticalLayout_6.addWidget(self.pbSpring2D)
        self.pbSpring6D = QtWidgets.QPushButton(self.widget_6)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/lincon6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSpring6D.setIcon(icon8)
        self.pbSpring6D.setFlat(True)
        self.pbSpring6D.setObjectName("pbSpring6D")
        self.verticalLayout_6.addWidget(self.pbSpring6D)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.gridLayout.addWidget(self.widget_6, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(MenuNodes)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.pbCable = QtWidgets.QPushButton(self.widget_3)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/cable.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbCable.setIcon(icon9)
        self.pbCable.setFlat(True)
        self.pbCable.setObjectName("pbCable")
        self.verticalLayout_3.addWidget(self.pbCable)
        self.pbSling = QtWidgets.QPushButton(self.widget_3)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/sling.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSling.setIcon(icon10)
        self.pbSling.setFlat(True)
        self.pbSling.setObjectName("pbSling")
        self.verticalLayout_3.addWidget(self.pbSling)
        self.pbShackle = QtWidgets.QPushButton(self.widget_3)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbShackle.setIcon(icon11)
        self.pbShackle.setFlat(True)
        self.pbShackle.setObjectName("pbShackle")
        self.verticalLayout_3.addWidget(self.pbShackle)
        self.pbBeam = QtWidgets.QPushButton(self.widget_3)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/beam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbBeam.setIcon(icon12)
        self.pbBeam.setFlat(True)
        self.pbBeam.setObjectName("pbBeam")
        self.verticalLayout_3.addWidget(self.pbBeam)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.gridLayout.addWidget(self.widget_3, 1, 3, 1, 1)
        self.widget_2 = QtWidgets.QWidget(MenuNodes)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.pbForce = QtWidgets.QPushButton(self.widget_2)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/force.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbForce.setIcon(icon13)
        self.pbForce.setFlat(True)
        self.pbForce.setObjectName("pbForce")
        self.verticalLayout_2.addWidget(self.pbForce)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.gridLayout.addWidget(self.widget_2, 0, 3, 1, 1)
        self.widget_7 = QtWidgets.QWidget(MenuNodes)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.pbVisual = QtWidgets.QPushButton(self.widget_7)
        self.pbVisual.setStyleSheet("text-align:left")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/visual.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbVisual.setIcon(icon14)
        self.pbVisual.setFlat(True)
        self.pbVisual.setObjectName("pbVisual")
        self.verticalLayout_7.addWidget(self.pbVisual)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.gridLayout.addWidget(self.widget_7, 1, 5, 1, 1)
        self.widget_4 = QtWidgets.QWidget(MenuNodes)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.pbTank = QtWidgets.QPushButton(self.widget_4)
        self.pbTank.setStyleSheet("text-align:left")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/tank.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbTank.setIcon(icon15)
        self.pbTank.setFlat(True)
        self.pbTank.setObjectName("pbTank")
        self.verticalLayout_4.addWidget(self.pbTank)
        self.pbBuoyancyShape = QtWidgets.QPushButton(self.widget_4)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/buoy_mesh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbBuoyancyShape.setIcon(icon16)
        self.pbBuoyancyShape.setFlat(True)
        self.pbBuoyancyShape.setObjectName("pbBuoyancyShape")
        self.verticalLayout_4.addWidget(self.pbBuoyancyShape)
        self.pbLinearBuoyancy = QtWidgets.QPushButton(self.widget_4)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/linhyd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbLinearBuoyancy.setIcon(icon17)
        self.pbLinearBuoyancy.setFlat(True)
        self.pbLinearBuoyancy.setObjectName("pbLinearBuoyancy")
        self.verticalLayout_4.addWidget(self.pbLinearBuoyancy)
        self.pbWaveInteraction = QtWidgets.QPushButton(self.widget_4)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/waveinteraction.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbWaveInteraction.setIcon(icon18)
        self.pbWaveInteraction.setFlat(True)
        self.pbWaveInteraction.setObjectName("pbWaveInteraction")
        self.verticalLayout_4.addWidget(self.pbWaveInteraction)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.gridLayout.addWidget(self.widget_4, 1, 0, 1, 1)

        self.retranslateUi(MenuNodes)
        QtCore.QMetaObject.connectSlotsByName(MenuNodes)

    def retranslateUi(self, MenuNodes):
        MenuNodes.setWindowTitle(QtWidgets.QApplication.translate("MenuNodes", "Form", None, -1))
        self.widget.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.label.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MenuNodes", "Structure", None, -1))
        self.pbPoint.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.pbPoint.setText(QtWidgets.QApplication.translate("MenuNodes", "Point", None, -1))
        self.pbCircle.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.pbCircle.setText(QtWidgets.QApplication.translate("MenuNodes", "Circle", None, -1))
        self.pbAxis.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.pbAxis.setText(QtWidgets.QApplication.translate("MenuNodes", "Axis", None, -1))
        self.pbBody.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.pbBody.setText(QtWidgets.QApplication.translate("MenuNodes", "Body", None, -1))
        self.pbGeometricContact.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.pbGeometricContact.setText(QtWidgets.QApplication.translate("MenuNodes", "Geometric contact", None, -1))
        self.widget_5.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.label_5.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MenuNodes", "Elastic Contact", None, -1))
        self.pbContactShape.setText(QtWidgets.QApplication.translate("MenuNodes", "Contact Shape", None, -1))
        self.pbContactBall.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.pbContactBall.setText(QtWidgets.QApplication.translate("MenuNodes", "Contact Ball", None, -1))
        self.widget_6.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.label_6.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MenuNodes", "Springs", None, -1))
        self.pbSpring2D.setText(QtWidgets.QApplication.translate("MenuNodes", "2D spring", None, -1))
        self.pbSpring6D.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.pbSpring6D.setText(QtWidgets.QApplication.translate("MenuNodes", "6D spring", None, -1))
        self.widget_3.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.label_3.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MenuNodes", "Steel", None, -1))
        self.pbCable.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.pbCable.setText(QtWidgets.QApplication.translate("MenuNodes", "Cable", None, -1))
        self.pbSling.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.pbSling.setText(QtWidgets.QApplication.translate("MenuNodes", "Sling", None, -1))
        self.pbShackle.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.pbShackle.setText(QtWidgets.QApplication.translate("MenuNodes", "Shackle", None, -1))
        self.pbBeam.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.pbBeam.setText(QtWidgets.QApplication.translate("MenuNodes", "Beam", None, -1))
        self.widget_2.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.label_2.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MenuNodes", "Loads", None, -1))
        self.pbForce.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.pbForce.setText(QtWidgets.QApplication.translate("MenuNodes", "Force", None, -1))
        self.widget_7.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.label_7.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MenuNodes", "Beauty", None, -1))
        self.pbVisual.setText(QtWidgets.QApplication.translate("MenuNodes", "Visual", None, -1))
        self.widget_4.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.label_4.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MenuNodes", "Fluid", None, -1))
        self.pbTank.setText(QtWidgets.QApplication.translate("MenuNodes", "Tank", None, -1))
        self.pbBuoyancyShape.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.pbBuoyancyShape.setText(QtWidgets.QApplication.translate("MenuNodes", "Buoyancy shape", None, -1))
        self.pbLinearBuoyancy.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.pbLinearBuoyancy.setText(QtWidgets.QApplication.translate("MenuNodes", "Linear buoyancy", None, -1))
        self.pbWaveInteraction.setStyleSheet(QtWidgets.QApplication.translate("MenuNodes", "text-align:left", None, -1))
        self.pbWaveInteraction.setText(QtWidgets.QApplication.translate("MenuNodes", "Wave interaction", None, -1))

