# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_area.ui',
# licensing of 'widget_area.ui' applies.
#
# Created: Wed Sep  1 08:45:43 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_frmArea(object):
    def setupUi(self, frmArea):
        frmArea.setObjectName("frmArea")
        frmArea.resize(151, 298)
        self.gridLayout_3 = QtWidgets.QGridLayout(frmArea)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(frmArea)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.Z = QtWidgets.QDoubleSpinBox(self.widget)
        self.Z.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.World))
        self.Z.setMinimum(-10.0)
        self.Z.setMaximum(10.0)
        self.Z.setSingleStep(0.1)
        self.Z.setObjectName("Z")
        self.gridLayout.addWidget(self.Z, 5, 1, 1, 1)
        self.Y = QtWidgets.QDoubleSpinBox(self.widget)
        self.Y.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.World))
        self.Y.setMinimum(-10.0)
        self.Y.setMaximum(10.0)
        self.Y.setSingleStep(0.1)
        self.Y.setObjectName("Y")
        self.gridLayout.addWidget(self.Y, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.X = QtWidgets.QDoubleSpinBox(self.widget)
        self.X.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.World))
        self.X.setMinimum(-10.0)
        self.X.setMaximum(10.0)
        self.X.setSingleStep(0.1)
        self.X.setObjectName("X")
        self.gridLayout.addWidget(self.X, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 6, 1, 1, 2)
        self.rbCylinder = QtWidgets.QRadioButton(frmArea)
        self.rbCylinder.setObjectName("rbCylinder")
        self.gridLayout_3.addWidget(self.rbCylinder, 7, 0, 1, 3)
        self.label = QtWidgets.QLabel(frmArea)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.Area = QtWidgets.QDoubleSpinBox(frmArea)
        self.Area.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.World))
        self.Area.setMaximum(10000.0)
        self.Area.setObjectName("Area")
        self.gridLayout_3.addWidget(self.Area, 3, 1, 1, 1)
        self.rbNoOrientation = QtWidgets.QRadioButton(frmArea)
        self.rbNoOrientation.setObjectName("rbNoOrientation")
        self.gridLayout_3.addWidget(self.rbNoOrientation, 4, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(frmArea)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(frmArea)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.Cd = QtWidgets.QDoubleSpinBox(frmArea)
        self.Cd.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.World))
        self.Cd.setMaximum(100.0)
        self.Cd.setObjectName("Cd")
        self.gridLayout_3.addWidget(self.Cd, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(frmArea)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 2, 1, 1)
        self.rbPlane = QtWidgets.QRadioButton(frmArea)
        self.rbPlane.setObjectName("rbPlane")
        self.gridLayout_3.addWidget(self.rbPlane, 5, 0, 1, 3)
        self.widget_2 = QtWidgets.QWidget(frmArea)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.Z_2 = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.Z_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.World))
        self.Z_2.setMinimum(-10.0)
        self.Z_2.setMaximum(10.0)
        self.Z_2.setSingleStep(0.1)
        self.Z_2.setObjectName("Z_2")
        self.gridLayout_2.addWidget(self.Z_2, 5, 1, 1, 1)
        self.Y_2 = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.Y_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.World))
        self.Y_2.setMinimum(-10.0)
        self.Y_2.setMaximum(10.0)
        self.Y_2.setSingleStep(0.1)
        self.Y_2.setObjectName("Y_2")
        self.gridLayout_2.addWidget(self.Y_2, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.X_2 = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.X_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.World))
        self.X_2.setMinimum(-10.0)
        self.X_2.setMaximum(10.0)
        self.X_2.setSingleStep(0.1)
        self.X_2.setObjectName("X_2")
        self.gridLayout_2.addWidget(self.X_2, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 8, 1, 1, 2)
        self.windcurrent = QtWidgets.QLabel(frmArea)
        self.windcurrent.setStyleSheet("")
        self.windcurrent.setFrameShape(QtWidgets.QFrame.Box)
        self.windcurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.windcurrent.setObjectName("windcurrent")
        self.gridLayout_3.addWidget(self.windcurrent, 0, 0, 1, 3)

        self.retranslateUi(frmArea)
        QtCore.QMetaObject.connectSlotsByName(frmArea)

    def retranslateUi(self, frmArea):
        frmArea.setWindowTitle(QtWidgets.QApplication.translate("frmArea", "Form", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("frmArea", "Z", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("frmArea", "Y", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("frmArea", "Plane normal:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("frmArea", "X", None, -1))
        self.rbCylinder.setText(QtWidgets.QApplication.translate("frmArea", "Cylindrical orientation", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("frmArea", "Cd", None, -1))
        self.rbNoOrientation.setText(QtWidgets.QApplication.translate("frmArea", "No orientation", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("frmArea", "[m2]", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("frmArea", "Area", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("frmArea", "[-]", None, -1))
        self.rbPlane.setText(QtWidgets.QApplication.translate("frmArea", "Plane orientation", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("frmArea", "Z", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("frmArea", "Y", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("frmArea", "Cylinder axis:", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("frmArea", "X", None, -1))
        self.windcurrent.setText(QtWidgets.QApplication.translate("frmArea", "TextLabel", None, -1))

