# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_modeshapes.ui',
# licensing of 'widget_modeshapes.ui' applies.
#
# Created: Mon Jan 20 16:06:35 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ModeShapesWidget(object):
    def setupUi(self, ModeShapesWidget):
        ModeShapesWidget.setObjectName("ModeShapesWidget")
        ModeShapesWidget.resize(1333, 385)
        self.gridLayout = QtWidgets.QGridLayout(ModeShapesWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(ModeShapesWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.gridLayout.addWidget(self.frame, 3, 2, 1, 4)
        self.line = QtWidgets.QFrame(ModeShapesWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(ModeShapesWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(ModeShapesWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 3, 1, 1)
        self.line_4 = QtWidgets.QFrame(ModeShapesWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(ModeShapesWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame_2, 3, 0, 1, 1)
        self.btnCalc = QtWidgets.QPushButton(ModeShapesWidget)
        self.btnCalc.setCheckable(False)
        self.btnCalc.setChecked(False)
        self.btnCalc.setObjectName("btnCalc")
        self.gridLayout.addWidget(self.btnCalc, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(ModeShapesWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 4, 1, 1)
        self.lblPeriod = QtWidgets.QLabel(ModeShapesWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblPeriod.setFont(font)
        self.lblPeriod.setObjectName("lblPeriod")
        self.gridLayout.addWidget(self.lblPeriod, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(ModeShapesWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 4, 1, 1)
        self.sliderSize = QtWidgets.QSlider(ModeShapesWidget)
        self.sliderSize.setMinimum(1)
        self.sliderSize.setMaximum(100)
        self.sliderSize.setProperty("value", 10)
        self.sliderSize.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSize.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.sliderSize.setObjectName("sliderSize")
        self.gridLayout.addWidget(self.sliderSize, 1, 5, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(ModeShapesWidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 0, 5, 1, 1)
        self.lblRads = QtWidgets.QLabel(ModeShapesWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblRads.setFont(font)
        self.lblRads.setObjectName("lblRads")
        self.gridLayout.addWidget(self.lblRads, 1, 2, 1, 1)
        self.lblError = QtWidgets.QLabel(ModeShapesWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblError.setFont(font)
        self.lblError.setStyleSheet("color:rgb(200, 0, 0)")
        self.lblError.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lblError.setTextFormat(QtCore.Qt.AutoText)
        self.lblError.setObjectName("lblError")
        self.gridLayout.addWidget(self.lblError, 1, 0, 1, 1)

        self.retranslateUi(ModeShapesWidget)
        QtCore.QMetaObject.connectSlotsByName(ModeShapesWidget)

    def retranslateUi(self, ModeShapesWidget):
        ModeShapesWidget.setWindowTitle(QtWidgets.QApplication.translate("ModeShapesWidget", "Form", None, -1))
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("ModeShapesWidget", "Exitation", None, -1))
        self.tableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("ModeShapesWidget", "Linear Inertia", None, -1))
        self.tableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("ModeShapesWidget", "Radius", None, -1))
        self.tableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("ModeShapesWidget", "Total inc. children", None, -1))
        self.tableWidget.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("ModeShapesWidget", "Stiffness", None, -1))
        self.tableWidget.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("ModeShapesWidget", "unconstrained", None, -1))
        self.tableWidget.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("ModeShapesWidget", "no-inertia", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("ModeShapesWidget", "Quick-fix model", None, -1))
        self.btnCalc.setText(QtWidgets.QApplication.translate("ModeShapesWidget", "Calculate Modeshapes", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("ModeShapesWidget", "Mode-shape", None, -1))
        self.lblPeriod.setText(QtWidgets.QApplication.translate("ModeShapesWidget", "Period", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("ModeShapesWidget", "Scale", None, -1))
        self.lblRads.setText(QtWidgets.QApplication.translate("ModeShapesWidget", "Frequency", None, -1))
        self.lblError.setText(QtWidgets.QApplication.translate("ModeShapesWidget", "warning/error", None, -1))

