# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_beam.ui',
# licensing of 'widget_beam.ui' applies.
#
# Created: Wed Oct  5 09:40:04 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_widget_beam(object):
    def setupUi(self, widget_beam):
        widget_beam.setObjectName("widget_beam")
        widget_beam.resize(460, 500)
        widget_beam.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(widget_beam)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frmMasterSlave = QtWidgets.QFrame(widget_beam)
        self.frmMasterSlave.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmMasterSlave.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmMasterSlave.setObjectName("frmMasterSlave")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frmMasterSlave)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sbnSegments = QtWidgets.QSpinBox(self.frmMasterSlave)
        self.sbnSegments.setMinimum(1)
        self.sbnSegments.setMaximum(1000)
        self.sbnSegments.setObjectName("sbnSegments")
        self.gridLayout_2.addWidget(self.sbnSegments, 4, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frmMasterSlave)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 4, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frmMasterSlave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(80, 0))
        self.label_9.setMaximumSize(QtCore.QSize(9999, 16777215))
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frmMasterSlave)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frmMasterSlave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(80, 0))
        self.label_11.setMaximumSize(QtCore.QSize(9999, 16777215))
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.widgetMain = QNodePicker(self.frmMasterSlave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetMain.sizePolicy().hasHeightForWidth())
        self.widgetMain.setSizePolicy(sizePolicy)
        self.widgetMain.setObjectName("widgetMain")
        self.gridLayout_2.addWidget(self.widgetMain, 0, 1, 1, 2)
        self.widgetSecondary = QNodePicker(self.frmMasterSlave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetSecondary.sizePolicy().hasHeightForWidth())
        self.widgetSecondary.setSizePolicy(sizePolicy)
        self.widgetSecondary.setObjectName("widgetSecondary")
        self.gridLayout_2.addWidget(self.widgetSecondary, 2, 1, 1, 2)
        self.verticalLayout.addWidget(self.frmMasterSlave)
        self.label_7 = QtWidgets.QLabel(widget_beam)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.frame = QtWidgets.QFrame(widget_beam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_3.setSizePolicy(sizePolicy)
        self.doubleSpinBox_3.setDecimals(0)
        self.doubleSpinBox_3.setMinimum(-999999999999.0)
        self.doubleSpinBox_3.setMaximum(99999999999999.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout.addWidget(self.doubleSpinBox_3, 5, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 6, 3, 1, 1)
        self.sbMass = QtWidgets.QDoubleSpinBox(self.frame)
        self.sbMass.setDecimals(5)
        self.sbMass.setMaximum(999999.0)
        self.sbMass.setSingleStep(0.1)
        self.sbMass.setObjectName("sbMass")
        self.gridLayout.addWidget(self.sbMass, 1, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 1, 3, 1, 1)
        self.doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_1.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_1.setSizePolicy(sizePolicy)
        self.doubleSpinBox_1.setDecimals(3)
        self.doubleSpinBox_1.setMinimum(-999999999999.0)
        self.doubleSpinBox_1.setMaximum(99999999999999.0)
        self.doubleSpinBox_1.setObjectName("doubleSpinBox_1")
        self.gridLayout.addWidget(self.doubleSpinBox_1, 0, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.doubleSpinBox_2.setDecimals(0)
        self.doubleSpinBox_2.setMinimum(-999999999999.0)
        self.doubleSpinBox_2.setMaximum(99999999999999.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 4, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 3, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_4.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_4.setSizePolicy(sizePolicy)
        self.doubleSpinBox_4.setDecimals(0)
        self.doubleSpinBox_4.setMinimum(-999999999999.0)
        self.doubleSpinBox_4.setMaximum(99999999999999.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout.addWidget(self.doubleSpinBox_4, 6, 1, 1, 2)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_5.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_5.setSizePolicy(sizePolicy)
        self.doubleSpinBox_5.setDecimals(0)
        self.doubleSpinBox_5.setMinimum(-999999999999.0)
        self.doubleSpinBox_5.setMaximum(99999999999999.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout.addWidget(self.doubleSpinBox_5, 2, 1, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.cbTensionOnly = QtWidgets.QCheckBox(self.frame)
        self.cbTensionOnly.setObjectName("cbTensionOnly")
        self.gridLayout.addWidget(self.cbTensionOnly, 3, 1, 1, 2)
        self.verticalLayout.addWidget(self.frame)
        self.label_8 = QtWidgets.QLabel(widget_beam)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(widget_beam)
        QtCore.QMetaObject.connectSlotsByName(widget_beam)
        widget_beam.setTabOrder(self.sbnSegments, self.doubleSpinBox_1)
        widget_beam.setTabOrder(self.doubleSpinBox_1, self.sbMass)
        widget_beam.setTabOrder(self.sbMass, self.doubleSpinBox_5)
        widget_beam.setTabOrder(self.doubleSpinBox_5, self.cbTensionOnly)
        widget_beam.setTabOrder(self.cbTensionOnly, self.doubleSpinBox_2)
        widget_beam.setTabOrder(self.doubleSpinBox_2, self.doubleSpinBox_3)
        widget_beam.setTabOrder(self.doubleSpinBox_3, self.doubleSpinBox_4)

    def retranslateUi(self, widget_beam):
        widget_beam.setWindowTitle(QtWidgets.QApplication.translate("widget_beam", "Form", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("widget_beam", "[-]", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("widget_beam", "Second connection", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("widget_beam", "Number of Segments", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("widget_beam", "First connection", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("widget_beam", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Properties (for total beam)</span></p></body></html>", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("widget_beam", "EIy", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("widget_beam", "[m]", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("widget_beam", "Length", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("widget_beam", "Mass", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("widget_beam", "[kN*m2]", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("widget_beam", "[kN*m2]", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("widget_beam", "GIp", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("widget_beam", "[mT]", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("widget_beam", "EIz", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("widget_beam", "[kN*m2]", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("widget_beam", "[kN]", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("widget_beam", "EA", None, -1))
        self.cbTensionOnly.setText(QtWidgets.QApplication.translate("widget_beam", "Tension only", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("widget_beam", "<html><head/><body><p>E(steel) is ~210 GPa = 210*10^6 kN/m2</p></body></html>", None, -1))

from DAVE.gui.helpers.qnodepicker import QNodePicker
