# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_con2d.ui',
# licensing of 'widget_con2d.ui' applies.
#
# Created: Thu Jul  2 20:34:21 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_widget_con2d(object):
    def setupUi(self, widget_con2d):
        widget_con2d.setObjectName("widget_con2d")
        widget_con2d.resize(343, 408)
        widget_con2d.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(widget_con2d)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frmMasterSlave = QtWidgets.QFrame(widget_con2d)
        self.frmMasterSlave.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmMasterSlave.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmMasterSlave.setObjectName("frmMasterSlave")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frmMasterSlave)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.frmMasterSlave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(80, 0))
        self.label_9.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.cbMasterAxis = QtWidgets.QComboBox(self.frmMasterSlave)
        self.cbMasterAxis.setObjectName("cbMasterAxis")
        self.gridLayout_2.addWidget(self.cbMasterAxis, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frmMasterSlave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(60, 0))
        self.label_10.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frmMasterSlave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(80, 0))
        self.label_11.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.cbSlaveAxis = QtWidgets.QComboBox(self.frmMasterSlave)
        self.cbSlaveAxis.setObjectName("cbSlaveAxis")
        self.gridLayout_2.addWidget(self.cbSlaveAxis, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frmMasterSlave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(60, 0))
        self.label_12.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.frmMasterSlave)
        self.frame = QtWidgets.QFrame(widget_con2d)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_1.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_1.setSizePolicy(sizePolicy)
        self.doubleSpinBox_1.setDecimals(3)
        self.doubleSpinBox_1.setMinimum(-999999999999.0)
        self.doubleSpinBox_1.setMaximum(99999999999999.0)
        self.doubleSpinBox_1.setObjectName("doubleSpinBox_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.doubleSpinBox_1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_4.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_4.setSizePolicy(sizePolicy)
        self.doubleSpinBox_4.setDecimals(3)
        self.doubleSpinBox_4.setMinimum(-999999999999.0)
        self.doubleSpinBox_4.setMaximum(99999999999999.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.doubleSpinBox_4)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        self.label = QtWidgets.QLabel(widget_con2d)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(widget_con2d)
        QtCore.QMetaObject.connectSlotsByName(widget_con2d)

    def retranslateUi(self, widget_con2d):
        widget_con2d.setWindowTitle(QtWidgets.QApplication.translate("widget_con2d", "Form", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("widget_con2d", "Main", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("widget_con2d", "[axis]", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("widget_con2d", "Secondary", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("widget_con2d", "[axis]", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("widget_con2d", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Linear stiffness</span></p></body></html>", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("widget_con2d", "kN/m", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("widget_con2d", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Angular stiffness</span></p></body></html>", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("widget_con2d", "kN.m/rad", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("widget_con2d", "2d-connector works on shortest distance and angle between two axis sytems.", None, -1))

