# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_sheave.ui',
# licensing of 'widget_sheave.ui' applies.
#
# Created: Thu Jul  2 20:34:21 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_widget_sheave(object):
    def setupUi(self, widget_sheave):
        widget_sheave.setObjectName("widget_sheave")
        widget_sheave.resize(315, 782)
        widget_sheave.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(widget_sheave)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(widget_sheave)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.sbRadius = QtWidgets.QDoubleSpinBox(widget_sheave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbRadius.sizePolicy().hasHeightForWidth())
        self.sbRadius.setSizePolicy(sizePolicy)
        self.sbRadius.setDecimals(3)
        self.sbRadius.setMinimum(-999999999999.0)
        self.sbRadius.setMaximum(99999999999999.0)
        self.sbRadius.setObjectName("sbRadius")
        self.verticalLayout.addWidget(self.sbRadius)
        self.label_7 = QtWidgets.QLabel(widget_sheave)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.frame = QtWidgets.QFrame(widget_sheave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sbAX = QtWidgets.QDoubleSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbAX.sizePolicy().hasHeightForWidth())
        self.sbAX.setSizePolicy(sizePolicy)
        self.sbAX.setDecimals(3)
        self.sbAX.setMinimum(-999999999999.0)
        self.sbAX.setMaximum(99999999999999.0)
        self.sbAX.setObjectName("sbAX")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sbAX)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.sbAY = QtWidgets.QDoubleSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbAY.sizePolicy().hasHeightForWidth())
        self.sbAY.setSizePolicy(sizePolicy)
        self.sbAY.setDecimals(3)
        self.sbAY.setMinimum(-999999999999.0)
        self.sbAY.setMaximum(99999999999999.0)
        self.sbAY.setObjectName("sbAY")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sbAY)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sbAZ = QtWidgets.QDoubleSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbAZ.sizePolicy().hasHeightForWidth())
        self.sbAZ.setSizePolicy(sizePolicy)
        self.sbAZ.setDecimals(3)
        self.sbAZ.setMinimum(-999999999999.0)
        self.sbAZ.setMaximum(99999999999999.0)
        self.sbAZ.setObjectName("sbAZ")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sbAZ)
        self.verticalLayout.addWidget(self.frame)
        self.label_8 = QtWidgets.QLabel(widget_sheave)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(widget_sheave)
        QtCore.QMetaObject.connectSlotsByName(widget_sheave)
        widget_sheave.setTabOrder(self.sbAX, self.sbAY)
        widget_sheave.setTabOrder(self.sbAY, self.sbAZ)

    def retranslateUi(self, widget_sheave):
        widget_sheave.setWindowTitle(QtWidgets.QApplication.translate("widget_sheave", "Form", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("widget_sheave", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Circle radius</span></p></body></html>", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("widget_sheave", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Axis direction</span></p></body></html>", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("widget_sheave", "X", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("widget_sheave", "Y", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("widget_sheave", "Z", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("widget_sheave", "<html><head/><body><p>Axis direction is defined in parent axis system.</p><p>Wire runs over the circle in positive direction (apply right hand rule on axis direction).</p></body></html>", None, -1))

