# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_tank.ui',
# licensing of 'widget_tank.ui' applies.
#
# Created: Thu Jan 14 19:53:08 2021
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(538, 323)
        Form.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbFreeFlooding = QtWidgets.QCheckBox(Form)
        self.cbFreeFlooding.setObjectName("cbFreeFlooding")
        self.verticalLayout.addWidget(self.cbFreeFlooding)
        self.widgetContents = QtWidgets.QWidget(Form)
        self.widgetContents.setObjectName("widgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.widgetContents)
        self.gridLayout.setContentsMargins(0, -1, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.widgetContents)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widgetContents)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.sbDenstiy = QtWidgets.QDoubleSpinBox(self.widgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbDenstiy.sizePolicy().hasHeightForWidth())
        self.sbDenstiy.setSizePolicy(sizePolicy)
        self.sbDenstiy.setDecimals(3)
        self.sbDenstiy.setMinimum(-999999999999.0)
        self.sbDenstiy.setMaximum(99999999999999.0)
        self.sbDenstiy.setObjectName("sbDenstiy")
        self.gridLayout.addWidget(self.sbDenstiy, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widgetContents)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.lblCapacity = QtWidgets.QLabel(self.widgetContents)
        self.lblCapacity.setObjectName("lblCapacity")
        self.gridLayout.addWidget(self.lblCapacity, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.sbVolume = QtWidgets.QDoubleSpinBox(self.widgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbVolume.sizePolicy().hasHeightForWidth())
        self.sbVolume.setSizePolicy(sizePolicy)
        self.sbVolume.setDecimals(3)
        self.sbVolume.setMinimum(-999999999999.0)
        self.sbVolume.setMaximum(99999999999999.0)
        self.sbVolume.setObjectName("sbVolume")
        self.gridLayout.addWidget(self.sbVolume, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.sbPercentage = QtWidgets.QDoubleSpinBox(self.widgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbPercentage.sizePolicy().hasHeightForWidth())
        self.sbPercentage.setSizePolicy(sizePolicy)
        self.sbPercentage.setDecimals(3)
        self.sbPercentage.setMinimum(0.0)
        self.sbPercentage.setMaximum(100.0)
        self.sbPercentage.setSingleStep(5.0)
        self.sbPercentage.setObjectName("sbPercentage")
        self.gridLayout.addWidget(self.sbPercentage, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.sbElevation = QtWidgets.QDoubleSpinBox(self.widgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbElevation.sizePolicy().hasHeightForWidth())
        self.sbElevation.setSizePolicy(sizePolicy)
        self.sbElevation.setDecimals(3)
        self.sbElevation.setMinimum(-999999999999.0)
        self.sbElevation.setMaximum(99999999999999.0)
        self.sbElevation.setObjectName("sbElevation")
        self.gridLayout.addWidget(self.sbElevation, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widgetContents)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 1, 1, 1)
        self.verticalLayout.addWidget(self.widgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.cbFreeFlooding.setText(QtWidgets.QApplication.translate("Form", "Free flooding (aka damaged)", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Fluid density</span></p></body></html>", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Contents density [mT/m3]", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Fill</span></p></body></html>", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Maximum capacity [m3]", None, -1))
        self.lblCapacity.setText(QtWidgets.QApplication.translate("Form", "Calculated", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Volume [m3]", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "Fill percentage [%]", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Global Elevation [m]", None, -1))
        self.label_8.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>Setting any of these values changes the amount of fluid in the tank. Global elevation may thus change if the vessel moves.</p></body></html>", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "note (hoover to show)", None, -1))

