# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_spmt.ui',
# licensing of 'widget_spmt.ui' applies.
#
# Created: Mon Jan 10 09:42:28 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SPMTwidget(object):
    def setupUi(self, SPMTwidget):
        SPMTwidget.setObjectName("SPMTwidget")
        SPMTwidget.resize(209, 350)
        self.gridLayout = QtWidgets.QGridLayout(SPMTwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(SPMTwidget)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(SPMTwidget)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 3)
        self.label = QtWidgets.QLabel(SPMTwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.sbRefExtension = QtWidgets.QDoubleSpinBox(SPMTwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbRefExtension.sizePolicy().hasHeightForWidth())
        self.sbRefExtension.setSizePolicy(sizePolicy)
        self.sbRefExtension.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.World))
        self.sbRefExtension.setFrame(True)
        self.sbRefExtension.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sbRefExtension.setDecimals(3)
        self.sbRefExtension.setMinimum(0.0)
        self.sbRefExtension.setMaximum(10.0)
        self.sbRefExtension.setSingleStep(0.1)
        self.sbRefExtension.setObjectName("sbRefExtension")
        self.gridLayout.addWidget(self.sbRefExtension, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(SPMTwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(SPMTwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.sbRefForce = QtWidgets.QDoubleSpinBox(SPMTwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbRefForce.sizePolicy().hasHeightForWidth())
        self.sbRefForce.setSizePolicy(sizePolicy)
        self.sbRefForce.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.World))
        self.sbRefForce.setDecimals(3)
        self.sbRefForce.setMinimum(0.0)
        self.sbRefForce.setMaximum(99999999999999.0)
        self.sbRefForce.setObjectName("sbRefForce")
        self.gridLayout.addWidget(self.sbRefForce, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(SPMTwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(SPMTwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.sbStiffness = QtWidgets.QDoubleSpinBox(SPMTwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbStiffness.sizePolicy().hasHeightForWidth())
        self.sbStiffness.setSizePolicy(sizePolicy)
        self.sbStiffness.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.World))
        self.sbStiffness.setDecimals(3)
        self.sbStiffness.setMinimum(0.0)
        self.sbStiffness.setMaximum(99999999999999.0)
        self.sbStiffness.setObjectName("sbStiffness")
        self.gridLayout.addWidget(self.sbStiffness, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(SPMTwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(SPMTwidget)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(SPMTwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.sbDY = QtWidgets.QDoubleSpinBox(SPMTwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbDY.sizePolicy().hasHeightForWidth())
        self.sbDY.setSizePolicy(sizePolicy)
        self.sbDY.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.World))
        self.sbDY.setDecimals(3)
        self.sbDY.setMinimum(0.0)
        self.sbDY.setMaximum(100.0)
        self.sbDY.setSingleStep(0.1)
        self.sbDY.setObjectName("sbDY")
        self.gridLayout.addWidget(self.sbDY, 6, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(SPMTwidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 6, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(SPMTwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.sbDX = QtWidgets.QDoubleSpinBox(SPMTwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbDX.sizePolicy().hasHeightForWidth())
        self.sbDX.setSizePolicy(sizePolicy)
        self.sbDX.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.World))
        self.sbDX.setDecimals(3)
        self.sbDX.setMinimum(0.0)
        self.sbDX.setMaximum(100.0)
        self.sbDX.setSingleStep(0.1)
        self.sbDX.setObjectName("sbDX")
        self.gridLayout.addWidget(self.sbDX, 7, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(SPMTwidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 7, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(SPMTwidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 8, 0, 1, 1)
        self.sbNY = QtWidgets.QSpinBox(SPMTwidget)
        self.sbNY.setObjectName("sbNY")
        self.gridLayout.addWidget(self.sbNY, 8, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(SPMTwidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 8, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(SPMTwidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 9, 0, 1, 1)
        self.sbNX = QtWidgets.QSpinBox(SPMTwidget)
        self.sbNX.setObjectName("sbNX")
        self.gridLayout.addWidget(self.sbNX, 9, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(SPMTwidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 9, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(SPMTwidget)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 10, 0, 1, 3)
        self.rbPerpendicular = QtWidgets.QRadioButton(SPMTwidget)
        self.rbPerpendicular.setObjectName("rbPerpendicular")
        self.gridLayout.addWidget(self.rbPerpendicular, 12, 0, 1, 3)
        self.rbVertical = QtWidgets.QRadioButton(SPMTwidget)
        self.rbVertical.setChecked(True)
        self.rbVertical.setObjectName("rbVertical")
        self.gridLayout.addWidget(self.rbVertical, 11, 0, 1, 3)

        self.retranslateUi(SPMTwidget)
        QtCore.QMetaObject.connectSlotsByName(SPMTwidget)

    def retranslateUi(self, SPMTwidget):
        SPMTwidget.setWindowTitle(QtWidgets.QApplication.translate("SPMTwidget", "Form", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("SPMTwidget", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Hydraulics</span></p></body></html>", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("SPMTwidget", "<html><head/><body>Hydraulic settings are defined by defining an reference force and extension as well as a stiffness.<br>If the SPMT is loaded with a force equal to the reference force then the average extension of the axles is the reference extension.<br/>The stiffness defines the stiffness of the whole SPMT, that is: all axles together.</body></html>", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("SPMTwidget", "Ref. extension", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("SPMTwidget", "[m]", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("SPMTwidget", "Ref. force", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("SPMTwidget", "[kN]", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("SPMTwidget", "Stiffness", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("SPMTwidget", "[kN/m]", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("SPMTwidget", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Axles</span></p></body></html>", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("SPMTwidget", "Spacing width", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("SPMTwidget", "[m]", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("SPMTwidget", "Spacing length", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("SPMTwidget", "[m]", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("SPMTwidget", "Number in width", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("SPMTwidget", "[-]", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("SPMTwidget", "Number in length", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("SPMTwidget", "[-]", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("SPMTwidget", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Friction/Break</span></p></body></html>", None, -1))
        self.rbPerpendicular.setText(QtWidgets.QApplication.translate("SPMTwidget", "Force perp. to contact plane (no friction)", None, -1))
        self.rbVertical.setText(QtWidgets.QApplication.translate("SPMTwidget", "Force vertical (friction)", None, -1))

