call c:\Anaconda\Library\bin\pyuic5.bat -x main_form.ui -o "..\src\virtualfloat\viewer_form.py"
call c:\Anaconda\Library\bin\pyuic5.bat -x widget_axis.ui -o "..\src\virtualfloat\widget_axis.py"
call c:\Anaconda\Library\bin\pyuic5.bat -x widget_body.ui -o "..\src\virtualfloat\widget_body.py"
call c:\Anaconda\Library\bin\pyuic5.bat -x widget_poi.ui -o "..\src\virtualfloat\widget_poi.py"
call c:\Anaconda\Library\bin\pyuic5.bat -x widget_cable.ui -o "..\src\virtualfloat\widget_cable.py"
call c:\Anaconda\Library\bin\pyuic5.bat -x addnode_form.ui -o "..\src\virtualfloat\addnode_form.py"
call c:\Anaconda\Library\bin\pyuic5.bat -x widget_name.ui -o "..\src\virtualfloat\widget_name.py"
call c:\Anaconda\Library\bin\pyuic5.bat -x widget_visual.ui -o "..\src\virtualfloat\widget_visual.py"
call c:\Anaconda\Library\bin\pyuic5.bat -x widget_force.ui -o "..\src\virtualfloat\widget_force.py"
call c:\Anaconda\Library\bin\pyuic5.bat -x widget_linhyd.ui -o "..\src\virtualfloat\widget_linhyd.py"
call c:\Anaconda\Library\bin\pyuic5.bat -x widget_lincon6.ui -o "..\src\virtualfloat\widget_lincon6.py"
call c:\Anaconda\Library\bin\pyuic5.bat -x widget_beam.ui -o "..\src\virtualfloat\widget_beam.py"
call c:\Anaconda\Library\bin\pyuic5.bat -x widget_con2d.ui -o "..\src\virtualfloat\widget_con2d.py"
call c:\Anaconda\Library\bin\pyrcc5.bat resources.qrc -o "..\src\resources_rc.py"