# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_animation.ui',
# licensing of 'frm_animation.ui' applies.
#
# Created: Thu Nov 28 14:40:04 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_AnimationWindow(object):
    def setupUi(self, AnimationWindow):
        AnimationWindow.setObjectName("AnimationWindow")
        AnimationWindow.resize(1787, 1211)
        AnimationWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(AnimationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame3d = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame3d.sizePolicy().hasHeightForWidth())
        self.frame3d.setSizePolicy(sizePolicy)
        self.frame3d.setSizeIncrement(QtCore.QSize(8, 8))
        self.frame3d.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3d.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3d.setObjectName("frame3d")
        self.horizontalLayout.addWidget(self.frame3d)
        AnimationWindow.setCentralWidget(self.centralwidget)
        self.dockWidget = QtWidgets.QDockWidget(AnimationWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.dockWidgetContents)
        self.horizontalSlider_2.setMinimum(1)
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setProperty("value", 10)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout.addWidget(self.horizontalSlider_2, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.dockWidgetContents)
        self.horizontalSlider.setOrientation(QtCore.Qt.Vertical)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 3, 0, 1, 1)
        self.lblRads = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblRads.setFont(font)
        self.lblRads.setObjectName("lblRads")
        self.gridLayout.addWidget(self.lblRads, 1, 0, 1, 1)
        self.lblPeriod = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblPeriod.setFont(font)
        self.lblPeriod.setObjectName("lblPeriod")
        self.gridLayout.addWidget(self.lblPeriod, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        AnimationWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(AnimationWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_2.sizePolicy().hasHeightForWidth())
        self.dockWidget_2.setSizePolicy(sizePolicy)
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents_2.setSizePolicy(sizePolicy)
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        AnimationWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_2)
        self.dockWidget_3 = QtWidgets.QDockWidget(AnimationWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_3.sizePolicy().hasHeightForWidth())
        self.dockWidget_3.setSizePolicy(sizePolicy)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        AnimationWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_3)
        self.dockWidget_4 = QtWidgets.QDockWidget(AnimationWindow)
        self.dockWidget_4.setObjectName("dockWidget_4")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblChangeDynamicInfo = QtWidgets.QLabel(self.dockWidgetContents_4)
        self.lblChangeDynamicInfo.setObjectName("lblChangeDynamicInfo")
        self.verticalLayout_2.addWidget(self.lblChangeDynamicInfo)
        self.tableDynProp = QtWidgets.QTableWidget(self.dockWidgetContents_4)
        self.tableDynProp.setObjectName("tableDynProp")
        self.tableDynProp.setColumnCount(13)
        self.tableDynProp.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableDynProp.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDynProp.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDynProp.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDynProp.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDynProp.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDynProp.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDynProp.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDynProp.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDynProp.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDynProp.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDynProp.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDynProp.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDynProp.setHorizontalHeaderItem(12, item)
        self.tableDynProp.horizontalHeader().setMinimumSectionSize(20)
        self.tableDynProp.verticalHeader().setVisible(True)
        self.verticalLayout_2.addWidget(self.tableDynProp)
        self.dockWidget_4.setWidget(self.dockWidgetContents_4)
        AnimationWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_4)

        self.retranslateUi(AnimationWindow)
        QtCore.QMetaObject.connectSlotsByName(AnimationWindow)

    def retranslateUi(self, AnimationWindow):
        AnimationWindow.setWindowTitle(QtWidgets.QApplication.translate("AnimationWindow", "MainWindow", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("AnimationWindow", "Scale", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("AnimationWindow", "Mode-shape", None, -1))
        self.lblRads.setText(QtWidgets.QApplication.translate("AnimationWindow", "Frequency", None, -1))
        self.lblPeriod.setText(QtWidgets.QApplication.translate("AnimationWindow", "Period", None, -1))
        self.dockWidget_2.setWindowTitle(QtWidgets.QApplication.translate("AnimationWindow", "Dynamic analysis details", None, -1))
        self.tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("AnimationWindow", "Exitation", None, -1))
        self.tableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("AnimationWindow", "Inertia", None, -1))
        self.tableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("AnimationWindow", "Radius", None, -1))
        self.tableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("AnimationWindow", "(children)", None, -1))
        self.tableWidget.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("AnimationWindow", "Stiffness", None, -1))
        self.tableWidget.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("AnimationWindow", "unconstrained", None, -1))
        self.tableWidget.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("AnimationWindow", "no-inertia", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("AnimationWindow", "Quick-fix model", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("AnimationWindow", "Update model", None, -1))
        self.dockWidget_4.setWindowTitle(QtWidgets.QApplication.translate("AnimationWindow", "Dynamic properties", None, -1))
        self.lblChangeDynamicInfo.setText(QtWidgets.QApplication.translate("AnimationWindow", "Note: For RigidBody type nodes the inertia properties are coupled to the weight properties.\n"
"Changing the intertia properties changes the weight properties as well", None, -1))
        self.tableDynProp.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("AnimationWindow", "F", None, -1))
        self.tableDynProp.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("AnimationWindow", "I", None, -1))
        self.tableDynProp.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("AnimationWindow", "X", None, -1))
        self.tableDynProp.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("AnimationWindow", "E", None, -1))
        self.tableDynProp.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("AnimationWindow", "D", None, -1))
        self.tableDynProp.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("AnimationWindow", " ", None, -1))
        self.tableDynProp.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("AnimationWindow", "Inertia (weight)", None, -1))
        self.tableDynProp.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("AnimationWindow", "x (cog)", None, -1))
        self.tableDynProp.horizontalHeaderItem(8).setText(QtWidgets.QApplication.translate("AnimationWindow", "y (cog)", None, -1))
        self.tableDynProp.horizontalHeaderItem(9).setText(QtWidgets.QApplication.translate("AnimationWindow", " (cog)", None, -1))
        self.tableDynProp.horizontalHeaderItem(10).setText(QtWidgets.QApplication.translate("AnimationWindow", "rxx", None, -1))
        self.tableDynProp.horizontalHeaderItem(11).setText(QtWidgets.QApplication.translate("AnimationWindow", "ryy", None, -1))
        self.tableDynProp.horizontalHeaderItem(12).setText(QtWidgets.QApplication.translate("AnimationWindow", "rzz", None, -1))

