# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_standard_assets.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1000, 800)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Dave_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout.setObjectName("formLayout")
        self.checkBox = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox)
        self.btnImport = QtWidgets.QPushButton(self.frame_4)
        self.btnImport.setDefault(True)
        self.btnImport.setObjectName("btnImport")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.btnImport)
        self.txtPrefix = QtWidgets.QLineEdit(self.frame_4)
        self.txtPrefix.setObjectName("txtPrefix")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.txtPrefix)
        self.label_19 = QtWidgets.QLabel(self.frame_4)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.verticalLayout.addWidget(self.frame_4)
        self.lblInfo = QtWidgets.QLabel(self.frame)
        self.lblInfo.setObjectName("lblInfo")
        self.verticalLayout.addWidget(self.lblInfo)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.verticalLayout.addWidget(self.frame_5)
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget.setProperty("showDropIndicator", False)
        self.listWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout.addWidget(self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame3d = QtWidgets.QFrame(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame3d.sizePolicy().hasHeightForWidth())
        self.frame3d.setSizePolicy(sizePolicy)
        self.frame3d.setAcceptDrops(False)
        self.frame3d.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame3d.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3d.setObjectName("frame3d")
        self.horizontalLayout_2.addWidget(self.frame3d)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.actionSave_scene = QtWidgets.QAction(MainWindow)
        self.actionSave_scene.setObjectName("actionSave_scene")
        self.actionImport_sub_scene = QtWidgets.QAction(MainWindow)
        self.actionImport_sub_scene.setObjectName("actionImport_sub_scene")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionHorizontal_camera = QtWidgets.QAction(MainWindow)
        self.actionHorizontal_camera.setObjectName("actionHorizontal_camera")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action2D_mode = QtWidgets.QAction(MainWindow)
        self.action2D_mode.setCheckable(True)
        self.action2D_mode.setObjectName("action2D_mode")
        self.actionDark_mode = QtWidgets.QAction(MainWindow)
        self.actionDark_mode.setCheckable(False)
        self.actionDark_mode.setObjectName("actionDark_mode")
        self.actionShow_visuals = QtWidgets.QAction(MainWindow)
        self.actionShow_visuals.setCheckable(True)
        self.actionShow_visuals.setChecked(True)
        self.actionShow_visuals.setObjectName("actionShow_visuals")
        self.actionShow_Geometry_elements = QtWidgets.QAction(MainWindow)
        self.actionShow_Geometry_elements.setCheckable(True)
        self.actionShow_Geometry_elements.setChecked(True)
        self.actionShow_Geometry_elements.setObjectName("actionShow_Geometry_elements")
        self.actionShow_force_applyting_element = QtWidgets.QAction(MainWindow)
        self.actionShow_force_applyting_element.setCheckable(True)
        self.actionShow_force_applyting_element.setChecked(True)
        self.actionShow_force_applyting_element.setObjectName("actionShow_force_applyting_element")
        self.actionSet_all_visible = QtWidgets.QAction(MainWindow)
        self.actionSet_all_visible.setObjectName("actionSet_all_visible")
        self.actionSet_all_hidden = QtWidgets.QAction(MainWindow)
        self.actionSet_all_hidden.setObjectName("actionSet_all_hidden")
        self.actionFull_refresh = QtWidgets.QAction(MainWindow)
        self.actionFull_refresh.setObjectName("actionFull_refresh")
        self.actionShow_water_plane = QtWidgets.QAction(MainWindow)
        self.actionShow_water_plane.setCheckable(True)
        self.actionShow_water_plane.setChecked(False)
        self.actionShow_water_plane.setObjectName("actionShow_water_plane")
        self.actionAdd_light = QtWidgets.QAction(MainWindow)
        self.actionAdd_light.setObjectName("actionAdd_light")
        self.actionShow_all_forces_at_same_size = QtWidgets.QAction(MainWindow)
        self.actionShow_all_forces_at_same_size.setCheckable(True)
        self.actionShow_all_forces_at_same_size.setChecked(True)
        self.actionShow_all_forces_at_same_size.setObjectName("actionShow_all_forces_at_same_size")
        self.actionIncrease_force_size = QtWidgets.QAction(MainWindow)
        self.actionIncrease_force_size.setObjectName("actionIncrease_force_size")
        self.actionDecrease_force_size = QtWidgets.QAction(MainWindow)
        self.actionDecrease_force_size.setObjectName("actionDecrease_force_size")
        self.actionIncrease_Geometry_size = QtWidgets.QAction(MainWindow)
        self.actionIncrease_Geometry_size.setObjectName("actionIncrease_Geometry_size")
        self.actionDecrease_Geometry_size = QtWidgets.QAction(MainWindow)
        self.actionDecrease_Geometry_size.setObjectName("actionDecrease_Geometry_size")
        self.actionPython_console = QtWidgets.QAction(MainWindow)
        self.actionPython_console.setObjectName("actionPython_console")
        self.actionGoal_seek = QtWidgets.QAction(MainWindow)
        self.actionGoal_seek.setObjectName("actionGoal_seek")
        self.actionStability_curve = QtWidgets.QAction(MainWindow)
        self.actionStability_curve.setObjectName("actionStability_curve")
        self.actionOptimize = QtWidgets.QAction(MainWindow)
        self.actionOptimize.setObjectName("actionOptimize")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.checkBox, self.btnImport)
        MainWindow.setTabOrder(self.btnImport, self.lineEdit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Standard assets"))
        self.checkBox.setText(_translate("MainWindow", "Place imported asset in a container axis"))
        self.btnImport.setText(_translate("MainWindow", "Import this asset"))
        self.label_19.setText(_translate("MainWindow", "Apply pre-fix to element names:"))
        self.lblInfo.setText(_translate("MainWindow", "Info"))
        self.label_2.setText(_translate("MainWindow", "Filter"))
        self.actionSave_scene.setText(_translate("MainWindow", "Save as"))
        self.actionImport_sub_scene.setText(_translate("MainWindow", "Import"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionHorizontal_camera.setText(_translate("MainWindow", "Level camera (make horizon horizontal)"))
        self.actionHorizontal_camera.setShortcut(_translate("MainWindow", "Alt+L"))
        self.action.setText(_translate("MainWindow", "---"))
        self.action2D_mode.setText(_translate("MainWindow", "2D mode"))
        self.actionDark_mode.setText(_translate("MainWindow", "Make darker"))
        self.actionDark_mode.setShortcut(_translate("MainWindow", "Alt+-"))
        self.actionShow_visuals.setText(_translate("MainWindow", "Show visuals"))
        self.actionShow_Geometry_elements.setText(_translate("MainWindow", "Show Geometry elements"))
        self.actionShow_force_applyting_element.setText(_translate("MainWindow", "Show non-geometry elements"))
        self.actionSet_all_visible.setText(_translate("MainWindow", "Set all visible"))
        self.actionSet_all_hidden.setText(_translate("MainWindow", "Set all hidden"))
        self.actionFull_refresh.setText(_translate("MainWindow", "Full refresh"))
        self.actionShow_water_plane.setText(_translate("MainWindow", "Show water-plane"))
        self.actionAdd_light.setText(_translate("MainWindow", "Make lighter"))
        self.actionAdd_light.setShortcut(_translate("MainWindow", "Alt+="))
        self.actionShow_all_forces_at_same_size.setText(_translate("MainWindow", "Show all forces same size (normalize)"))
        self.actionIncrease_force_size.setText(_translate("MainWindow", "Increase force size"))
        self.actionIncrease_force_size.setShortcut(_translate("MainWindow", "Alt+]"))
        self.actionDecrease_force_size.setText(_translate("MainWindow", "Decrease force size"))
        self.actionDecrease_force_size.setShortcut(_translate("MainWindow", "Alt+["))
        self.actionIncrease_Geometry_size.setText(_translate("MainWindow", "Increase Geometry size (poi, axis)"))
        self.actionIncrease_Geometry_size.setShortcut(_translate("MainWindow", "Alt+Shift+]"))
        self.actionDecrease_Geometry_size.setText(_translate("MainWindow", "Decrease Geometry size"))
        self.actionDecrease_Geometry_size.setShortcut(_translate("MainWindow", "Alt+Shift+["))
        self.actionPython_console.setText(_translate("MainWindow", "Python console"))
        self.actionGoal_seek.setText(_translate("MainWindow", "Goal-seek (one variable)"))
        self.actionStability_curve.setText(_translate("MainWindow", "Stability-curve"))
        self.actionOptimize.setText(_translate("MainWindow", "TODO: Optimize (multiple variables)"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

