# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_cable.ui',
# licensing of 'widget_cable.ui' applies.
#
# Created: Thu Oct 31 16:19:27 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Cable_form(object):
    def setupUi(self, Cable_form):
        Cable_form.setObjectName("Cable_form")
        Cable_form.resize(398, 347)
        self.verticalLayout = QtWidgets.QVBoxLayout(Cable_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(Cable_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_7.setAutoFillBackground(False)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.frame_2 = QtWidgets.QFrame(Cable_form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_2.setDecimals(3)
        self.doubleSpinBox_2.setMinimum(-1e+18)
        self.doubleSpinBox_2.setMaximum(999999999999.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_1.setDecimals(3)
        self.doubleSpinBox_1.setMinimum(-1e+18)
        self.doubleSpinBox_1.setMaximum(999999999999.0)
        self.doubleSpinBox_1.setObjectName("doubleSpinBox_1")
        self.gridLayout.addWidget(self.doubleSpinBox_1, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(Cable_form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setWordWrap(True)
        self.label_3.setIndent(-1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnAdd = QtWidgets.QPushButton(self.frame_3)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.btnRemove = QtWidgets.QPushButton(self.frame_3)
        self.btnRemove.setObjectName("btnRemove")
        self.horizontalLayout_2.addWidget(self.btnRemove)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.poiLayout = QtWidgets.QVBoxLayout()
        self.poiLayout.setObjectName("poiLayout")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.poiLayout.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.poiLayout.addWidget(self.comboBox_2)
        self.verticalLayout_2.addLayout(self.poiLayout)
        self.verticalLayout.addWidget(self.frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 226, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(Cable_form)
        QtCore.QMetaObject.connectSlotsByName(Cable_form)
        Cable_form.setTabOrder(self.doubleSpinBox_1, self.doubleSpinBox_2)
        Cable_form.setTabOrder(self.doubleSpinBox_2, self.btnAdd)
        Cable_form.setTabOrder(self.btnAdd, self.btnRemove)
        Cable_form.setTabOrder(self.btnRemove, self.comboBox)
        Cable_form.setTabOrder(self.comboBox, self.comboBox_2)

    def retranslateUi(self, Cable_form):
        Cable_form.setWindowTitle(QtWidgets.QApplication.translate("Cable_form", "Form", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Cable_form", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Cable properties</span></p></body></html>", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Cable_form", "Length at rest [m]", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Cable_form", "Stiffness EA [kN/m]", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Cable_form", "<html><head/><body><p>Points of the cable</p></body></html>", None, -1))
        self.btnAdd.setText(QtWidgets.QApplication.translate("Cable_form", "Add", None, -1))
        self.btnRemove.setText(QtWidgets.QApplication.translate("Cable_form", "Remove", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("Cable_form", "Item1", None, -1))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("Cable_form", "Item2", None, -1))
        self.comboBox.setItemText(3, QtWidgets.QApplication.translate("Cable_form", "Item3", None, -1))
        self.comboBox_2.setItemText(1, QtWidgets.QApplication.translate("Cable_form", "Item1", None, -1))
        self.comboBox_2.setItemText(2, QtWidgets.QApplication.translate("Cable_form", "Item2", None, -1))
        self.comboBox_2.setItemText(3, QtWidgets.QApplication.translate("Cable_form", "Item3", None, -1))

